

services:
  - type: web
    name: selenium-hub
    runtime: image
    plan: free
    region: frankfurt
    image:
      url: docker.io/selenium/hub:latest
    envVars:
      - key:  PORT
        value: 4444
      - key: SUBSCRIBE_PORT
        value: 4443
      - key: PUBLISH_PORT
        value: 4442
      - key: SE_OTEL_EXPORTER_ENDPOINT
        value: ""
      - key: SE_OTEL_TRACES_EXPORTER
        value: none
  - type: web
    name: chrome-1
    runtime: image
    plan: free
    region: frankfurt
    image:
      url: docker.io/selenium/node-chrome
    envVars:
      - key: SE_EVENT_BUS_HOST
        value: 10.217.248.162
      - key: SE_EVENT_BUS_PUBLISH_PORT
        fromService:
          name: selenium-hub
          type: web
          envVarKey: PUBLISH_PORT
      - key: SE_EVENT_BUS_SUBSCRIBE_PORT
        fromService:
          name: selenium-hub
          type: web
          envVarKey: SUBSCRIBE_PORT
      - key: SE_OTEL_EXPORTER_ENDPOINT
        value: ""
  - type: web
    name: chrome-2
    runtime: image
    plan: free
    region: frankfurt
    image:
      url: docker.io/selenium/node-chrome
    envVars:
      - key: SE_EVENT_BUS_HOST
        value: 10.217.248.162
      - key: SE_EVENT_BUS_PUBLISH_PORT
        fromService:
          name: selenium-hub
          type: web
          envVarKey: PUBLISH_PORT
      - key: SE_EVENT_BUS_SUBSCRIBE_PORT
        fromService:
          name: selenium-hub
          type: web
          envVarKey: SUBSCRIBE_PORT
      - key: SE_OTEL_EXPORTER_ENDPOINT
        value: ""
  - type: web
    name: chrome-3
    runtime: image
    plan: free
    region: frankfurt
    image:
      url: docker.io/selenium/node-chrome
    envVars:
      - key: SE_EVENT_BUS_HOST
        value: 10.217.248.162
      - key: SE_EVENT_BUS_PUBLISH_PORT
        fromService:
          name: selenium-hub
          type: web
          envVarKey: PUBLISH_PORT
      - key: SE_EVENT_BUS_SUBSCRIBE_PORT
        fromService:
          name: selenium-hub
          type: web
          envVarKey: SUBSCRIBE_PORT
      - key: SE_OTEL_EXPORTER_ENDPOINT
        value: ""