services:
  - type: web
    name: selenium-hub
    runtime: image
    plan: free
    region: frankfurt
    image:
      url: docker.io/selenium/hub:latest
    envVars:
      - key: SE_EVENT_BUS_HOST
        value: "selenium-hub"
      - key: SE_EVENT_BUS_PUBLISH_PORT
        value: "4442"
      - key: SE_EVENT_BUS_SUBSCRIBE_PORT
        value: "4443"
  - type: web
    name: chrome-1
    runtime: image
    plan: free
    region: frankfurt
    image:
      url: docker.io/selenium/node-chrome
    envVars:
      - key: SE_EVENT_BUS_HOST
        value: "selenium-hub"
      - key: SE_EVENT_BUS_PUBLISH_PORT
        value: "4442"
      - key: SE_EVENT_BUS_SUBSCRIBE_PORT
        value: "4443"
  - type: web
    name: chrome-2
    runtime: image
    plan: free
    region: frankfurt
    image:
      url: docker.io/selenium/node-chrome
    envVars:
      - key: SE_EVENT_BUS_HOST
        value: "selenium-hub"
      - key: SE_EVENT_BUS_PUBLISH_PORT
        value: "4442"
      - key: SE_EVENT_BUS_SUBSCRIBE_PORT
        value: "4443"
  - type: web
    name: chrome-3
    runtime: image
    plan: free
    region: frankfurt
    image:
      url: docker.io/selenium/node-chrome
    envVars:
      - key: SE_EVENT_BUS_HOST
        value: "selenium-hub"
      - key: SE_EVENT_BUS_PUBLISH_PORT
        value: "4442"
      - key: SE_EVENT_BUS_SUBSCRIBE_PORT
        value: "4443"
  - type: web
    name: chrome-4
    runtime: image
    plan: free
    region: frankfurt
    image:
      url: docker.io/selenium/node-chrome
    envVars:
      - key: SE_EVENT_BUS_HOST
        value: "selenium-hub"
      - key: SE_EVENT_BUS_PUBLISH_PORT
        value: "4442"
      - key: SE_EVENT_BUS_SUBSCRIBE_PORT
        value: "4443"
  