spring:
  datasource:
    url: jdbc:mysql://mysql:3306/mydb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  mvc:
    async:
      request-timeout: 300000
  servlet:
    multipart:
      max-request-size: 100MB
parser:
  threads-amnt: ${threads-amnt}
  remote-chrome-1: ${CHROME_1}
  remote-chrome-2: ${CHROME_2}
  remote-chrome-3: ${CHROME_3}
frontend:
  url: ${FE_URL}