spring:
  mvc:
    async:
      request-timeout: 300000
parser:
  threads-amnt: 3
  remote-chrome-1: ${CHROME_1}
  remote-chrome-2: ${CHROME_2}
  remote-chrome-3: ${CHROME_3}
frontend:
  url: ${FE_URL}